.\" $OpenBSD: busybeed.c v.1.00 2016/11/20 15:41:17 baseprime Exp $
.\" 
.\" Copyright (c) 2016 Tracey Emery <tracey@traceyemery.com>
.\" 
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\" 
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\" 

.Dd $Mdocdate: November 21, 2016 $
.Dt BUSYBEED 1
.Os
.Sh NAME
.Nm busybeed
.Nd serial device control utility
.Sh SYNOPSIS
.Nm busybeed
.Op Fl sv
.Op Fl d Ar host : Ns Ar port
.Op Fl f Ar device
.Op Ar command args ...
.Sh DESCRIPTION
The
.Nm
program is a serial device control utility,
with support password protection and readable names. 
.Pp

