#!/bin/sh

cdev="cua."
tdev="tty."
#IFS="|"

devices[0]="A800HGEI|databee"

DEVCLASS=$1
DEVNAME=$2

case $DEVCLASS in
5)
	# tty device
	for i in ${devices[@]};
	do
		driver=
		IFS="|"
		set -A device $i
		serial=${device[0]}
		cname=$cdev${device[1]}
		tname=$tdev${device[1]}
		driver=$(usbdevs -dv | grep -A1 $serial | grep -v $serial | tr -s " ")
		if [[ -n $driver ]]; then
			clndev="/dev/cuaU$(dmesg | grep $driver | tail -1 | cut -d' ' -f1 | grep -o [0-9])"
			tlndev="/dev/ttyU$(dmesg | grep $driver | tail -1 | cut -d' ' -f1 | grep -o [0-9])"
			cfndev="/dev/$cname"
			tfndev="/dev/$tname"
			if [[ -e "$cfndev" ]] || [[ -e "$tfndev" ]]; then
				logger -i "attach: usb-serial device not in list"
			else
				ln -s $clndev $cfndev
				ln -s $tlndev $tfndev
				logger -i "attach: attached $cfndev"
				logger -i "attach: attached $tfndev"
			fi
		else
			logger -i "attach: hotplug attach error"
		fi
	done
;;
esac

exit 0
