#!/bin/sh

dev="tty."
#IFS="|"

// array of devices to find by iSerialNumber and a name

devices[0]="A800HGEI|databee"

DEVCLASS=$1
DEVNAME=$2

case $DEVCLASS in
5)
	# tty device
	for i in ${devices[@]};
	do
		driver=
		IFS="|"
		set -A device $i
		serial=${device[0]}
		name=$dev${device[1]}
		driver=$(usbdevs -dv | grep -A1 $serial | grep -v $serial | tr -s " ")
		if [[ -n $driver ]]; then
			lndev="/dev/ttyU$(dmesg | grep $driver | tail -1 | cut -d' ' -f1 | grep -o [0-9])"
			fndev="/dev/$name"
			if [[ -e "$fndev" ]]; then
				logger -i "attach: usb-serial device not in list"
			else
				ln -s $lndev $fndev
				logger -i "attach: attached $fndev"
			fi
		else
			logger -i "attach: hotplug attach error"
		fi
	done
;;
esac

exit 0
