#!/bin/sh

dev="tty."
#IFS="|"

// array of devices to find by iSerialNumber and a name

devices[0]="A800HGEI|databee"

DEVCLASS=$1
DEVNAME=$2

case $DEVCLASS in
5)
	# tty device
	for i in ${devices[@]};
	do
		driver=
		IFS="|"
		set -A device $i
		serial=${device[0]};
		name=$dev${device[1]};
		driver=$(usbdevs -dv | grep -A1 $serial | grep -v $serial | tr -s " ")
		if [[ -n $driver ]]; then
			lndev="/dev/ttyU$(dmesg | grep $driver | tail -1 | cut -d' ' -f1 | grep -o [0-9])"
			fndev="/dev/$name"
			if [[ -e "$fndev" ]]; then
				echo "usb-serial device not in list" >> /var/log/hotplug.attach;
			else
				ln -s $lndev $fndev
				echo "attached $fndev" >> /var/log/hotplug.attach;
			fi
		else
			echo "hotplug attach error" >> /var/log/hotplug.attach
		fi
	done
;;
esac

exit 0
