#!/bin/sh

cdev="cua."
tdev="tty."
#IFS="|"

devices[0]="A800HGEI|databee"

DEVCLASS=$1
DEVNAME=$2

case $DEVCLASS in
5)
	# tty device
	for i in ${devices[@]};
	do
		driver=
		IFS="|"
		set -A device $i
		serial=${device[0]}
		cname=$cdev${device[1]}
		tname=$tdev${device[1]}
		driver=$(usbdevs -dv | grep -A1 $serial | grep -v $serial | tr -s " ")
		cfndev="/dev/$cname"
		tfndev="/dev/$tname"
		if [[ -n $driver ]]; then
			logger -i "detach: usb-serial device not in list"
		else
			rm $cfndev
			rm $tfndev
			logger -i "detach: $cfndev removed"
			logger -i "detach: $tfndev removed"
		fi		
	done
;;
esac

exit 0
