#!/bin/sh

dev="tty."
#IFS="|"

// array of devices to find by iSerialNumber and a name

devices[0]="A800HGEI|databee"

DEVCLASS=$1
DEVNAME=$2

case $DEVCLASS in
5)
	# tty device
	for i in ${devices[@]};
	do
		driver=
		IFS="|"
		set -A device $i
		serial=${device[0]};
		name=$dev${device[1]};
		driver=$(usbdevs -dv | grep -A1 $serial | grep -v $serial | tr -s " ");
		fndev="/dev/$name"
		if [[ -n $driver ]]; then
			echo "usb-serial device not in list" >> /var/log/hotplug.detach
		else
			rm $fndev
			echo "$fndev removed" >> /var/log/hotplug.detach
		fi		
	done
;;
esac

exit 0
